### ISSUE TITLE
Update Data

### ISSUE THREAD

**Issue by dwillis** [outside-edge/asymmetry#18]
### Matches

- [x] Ensure existing scripts can run and fix if needed
- [x] Compare new output of matches json files with previous ones
- [x] Generate new `all_matches.json` file
- [x] Upgrade to Python 3
- [x] Generate master CSV file (along with any fixes to cricinfo parser)

### Grounds

- [ ] Ensure existing scripts can run and fix if needed
- [ ] Upgrade to Python 3

### Rankings

- [ ] Ensure existing scripts can run and fix if needed
- [ ] Upgrade to Python 3

**Comment by soodoku** [comment]
@dwillis: adding one more to the above: convert to github actions
